//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ss.Internal.Management.Server.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ss.Internal.Management.Server.Localization.Resources.Strings_es", typeof(Strings_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BackToAuto {
            get {
                return ResourceManager.GetString("BackToAuto", resourceCulture);
            }
        }
        
        internal static string BanCall {
            get {
                return ResourceManager.GetString("BanCall", resourceCulture);
            }
        }
        
        internal static string BlueBanned {
            get {
                return ResourceManager.GetString("BlueBanned", resourceCulture);
            }
        }
        
        internal static string BluePicked {
            get {
                return ResourceManager.GetString("BluePicked", resourceCulture);
            }
        }
        
        internal static string BlueWins {
            get {
                return ResourceManager.GetString("BlueWins", resourceCulture);
            }
        }
        
        internal static string EngagingAuto {
            get {
                return ResourceManager.GetString("EngagingAuto", resourceCulture);
            }
        }
        
        internal static string MatchWin {
            get {
                return ResourceManager.GetString("MatchWin", resourceCulture);
            }
        }
        
        internal static string NotEnoughArgs {
            get {
                return ResourceManager.GetString("NotEnoughArgs", resourceCulture);
            }
        }
        
        internal static string Panic {
            get {
                return ResourceManager.GetString("Panic", resourceCulture);
            }
        }
        
        internal static string PickCall {
            get {
                return ResourceManager.GetString("PickCall", resourceCulture);
            }
        }
        
        internal static string PropertiesNotInit {
            get {
                return ResourceManager.GetString("PropertiesNotInit", resourceCulture);
            }
        }
        
        internal static string RedBanned {
            get {
                return ResourceManager.GetString("RedBanned", resourceCulture);
            }
        }
        
        internal static string RedPicked {
            get {
                return ResourceManager.GetString("RedPicked", resourceCulture);
            }
        }
        
        internal static string RedWins {
            get {
                return ResourceManager.GetString("RedWins", resourceCulture);
            }
        }
        
        internal static string SecondBanRound {
            get {
                return ResourceManager.GetString("SecondBanRound", resourceCulture);
            }
        }
        
        internal static string SuccessfulFirstBan {
            get {
                return ResourceManager.GetString("SuccessfulFirstBan", resourceCulture);
            }
        }
        
        internal static string SuccessfulFirstPick {
            get {
                return ResourceManager.GetString("SuccessfulFirstPick", resourceCulture);
            }
        }
        
        internal static string QualifiersAutoEngage {
            get {
                return ResourceManager.GetString("QualifiersAutoEngage", resourceCulture);
            }
        }
        
        internal static string QualifiersOver {
            get {
                return ResourceManager.GetString("QualifiersOver", resourceCulture);
            }
        }
    }
}
