//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ss.Internal.Management.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ss.Internal.Management.Server.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto already engaged. Disable it with &apos;&gt;stop&apos;..
        /// </summary>
        internal static string AutoAlreadyEngaged {
            get {
                return ResourceManager.GetString("AutoAlreadyEngaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto is already not engaged..
        /// </summary>
        internal static string AutoAlreadyStopped {
            get {
                return ResourceManager.GetString("AutoAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available: {0}.
        /// </summary>
        internal static string AvailableMaps {
            get {
                return ResourceManager.GetString("AvailableMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going back to auto mode. Starting soon....
        /// </summary>
        internal static string BackToAuto {
            get {
                return ResourceManager.GetString("BackToAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please {0}, state in chat your BAN (eg.: NM1, HD2).
        /// </summary>
        internal static string BanCall {
            get {
                return ResourceManager.GetString("BanCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Blue has banned {0}..
        /// </summary>
        internal static string BlueBanned {
            get {
                return ResourceManager.GetString("BlueBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Blue has picked {0}..
        /// </summary>
        internal static string BluePicked {
            get {
                return ResourceManager.GetString("BluePicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Blue has requested a timeout. Time will be added after current timer runs out.
        /// </summary>
        internal static string BlueTimeout {
            get {
                return ResourceManager.GetString("BlueTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Blue wins the map! ({0} vs {1}).
        /// </summary>
        internal static string BlueWins {
            get {
                return ResourceManager.GetString("BlueWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting channel and killing thread....
        /// </summary>
        internal static string DeletingChannel {
            get {
                return ResourceManager.GetString("DeletingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engaging autoreferee mode for Elimination Stage, Lobby {0}.
        /// </summary>
        internal static string EngagingAuto {
            get {
                return ResourceManager.GetString("EngagingAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while executing AutoRef: `{0}`.
        /// </summary>
        internal static string ErrAutoref {
            get {
                return ResourceManager.GetString("ErrAutoref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Channel with ID {0} couldn&apos;t be found.
        /// </summary>
        internal static string ErrChannelNotFound {
            get {
                return ResourceManager.GetString("ErrChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while initializing AutoRef: {0}.
        /// </summary>
        internal static string ErrInitAutoref {
            get {
                return ResourceManager.GetString("ErrInitAutoref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Error**: File must be `.txt` or `.csv`.
        /// </summary>
        internal static string ErrorNotCorrectFileExtension {
            get {
                return ResourceManager.GetString("ErrorNotCorrectFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match `{0}` is already ongoing..
        /// </summary>
        internal static string MatchAlreadyCreated {
            get {
                return ResourceManager.GetString("MatchAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match `{0}` started in its corresponding thread..
        /// </summary>
        internal static string MatchCreated {
            get {
                return ResourceManager.GetString("MatchCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match finished. Locking thread &lt;#{0}&gt;....
        /// </summary>
        internal static string MatchFinishedGlobal {
            get {
                return ResourceManager.GetString("MatchFinishedGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **The match has finished.** This thread will be locked..
        /// </summary>
        internal static string MatchFinishedThread {
            get {
                return ResourceManager.GetString("MatchFinishedThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing up closure of match `{0}`....
        /// </summary>
        internal static string MatchFinishingUp {
            get {
                return ResourceManager.GetString("MatchFinishingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match `{0}` was not found in the database..
        /// </summary>
        internal static string MatchNotFound {
            get {
                return ResourceManager.GetString("MatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GGWP! {0} wins the match!.
        /// </summary>
        internal static string MatchWin {
            get {
                return ResourceManager.GetString("MatchWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough arguments..
        /// </summary>
        internal static string NotEnoughArgs {
            get {
                return ResourceManager.GetString("NotEnoughArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@&amp;{0}&gt;, {1} has requested human intervention. Auto mode has been disabled, resume it with !panic_over.
        /// </summary>
        internal static string Panic {
            get {
                return ResourceManager.GetString("Panic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please {0}, state in chat your PICK (eg.: NM1, HD2).
        /// </summary>
        internal static string PickCall {
            get {
                return ResourceManager.GetString("PickCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties not initialized. Set both first_ban and first_pick.
        /// </summary>
        internal static string PropertiesNotInit {
            get {
                return ResourceManager.GetString("PropertiesNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engaging autoreferee mode for Qualifiers, Lobby {0}. Use &apos;!panic&apos; if you need human intervention and a referee will get back to you ASAP.
        /// </summary>
        internal static string QualifiersAutoEngage {
            get {
                return ResourceManager.GetString("QualifiersAutoEngage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifiers lobby finished. Thank you for playing!.
        /// </summary>
        internal static string QualifiersOver {
            get {
                return ResourceManager.GetString("QualifiersOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Red has banned {0}..
        /// </summary>
        internal static string RedBanned {
            get {
                return ResourceManager.GetString("RedBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red has picked {0}..
        /// </summary>
        internal static string RedPicked {
            get {
                return ResourceManager.GetString("RedPicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Red has requested a timeout. Time will be added after current timer runs out.
        /// </summary>
        internal static string RedTimeout {
            get {
                return ResourceManager.GetString("RedTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Red wins the map! ({0} vs {1}).
        /// </summary>
        internal static string RedWins {
            get {
                return ResourceManager.GetString("RedWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee {0} added/updated in the database \n- OsuID: {1}\n- DiscordID: {2}.
        /// </summary>
        internal static string RefAddedToDb {
            get {
                return ResourceManager.GetString("RefAddedToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee **{0}** has been successfully assigned to match `{1}`.
        /// </summary>
        internal static string RefAssignedSuccessfully {
            get {
                return ResourceManager.GetString("RefAssignedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee `{0}` doesn&apos;t exist in database. Use `/linkirc` to add them..
        /// </summary>
        internal static string RefDoesntExist {
            get {
                return ResourceManager.GetString("RefDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout requested by the referee of the match. Time will be added after the timer runs out.
        /// </summary>
        internal static string RefTimeout {
            get {
                return ResourceManager.GetString("RefTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second ban round is about to start.
        /// </summary>
        internal static string SecondBanRound {
            get {
                return ResourceManager.GetString("SecondBanRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto is engaged, disable auto mode to manually set maps..
        /// </summary>
        internal static string SetMapFail {
            get {
                return ResourceManager.GetString("SetMapFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigns the given referee to a certain match..
        /// </summary>
        internal static string SlashCommandAssignRef {
            get {
                return ResourceManager.GetString("SlashCommandAssignRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizes a match environment and archives the thread where it took place.
        /// </summary>
        internal static string SlashCommandEndRef {
            get {
                return ResourceManager.GetString("SlashCommandEndRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a .csv file with LeoFLT&apos;s tool to parse it and save the scores.
        /// </summary>
        internal static string SlashCommandImportScoresPrivate {
            get {
                return ResourceManager.GetString("SlashCommandImportScoresPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your IRC credentials to make use of them to create matches.
        /// </summary>
        internal static string SlashCommandLinkIrc {
            get {
                return ResourceManager.GetString("SlashCommandLinkIrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a new match interface in between discord and Bancho, using the IRC credentials for a given referee..
        /// </summary>
        internal static string SlashCommandStartRef {
            get {
                return ResourceManager.GetString("SlashCommandStartRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping auto mode....
        /// </summary>
        internal static string StoppingAuto {
            get {
                return ResourceManager.GetString("StoppingAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set first_ban successfully.
        /// </summary>
        internal static string SuccessfulFirstBan {
            get {
                return ResourceManager.GetString("SuccessfulFirstBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set first_pick successfully.
        /// </summary>
        internal static string SuccessfulFirstPick {
            get {
                return ResourceManager.GetString("SuccessfulFirstPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red timeout available: {0} | Blue timeout available: {1}.
        /// </summary>
        internal static string TimeoutAvailable {
            get {
                return ResourceManager.GetString("TimeoutAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting timeout, remember to be ready/pick/ban before it runs out!.
        /// </summary>
        internal static string TimeoutStart {
            get {
                return ResourceManager.GetString("TimeoutStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel created for referee: **{0}**. Starting worker....
        /// </summary>
        internal static string WorkerInit {
            get {
                return ResourceManager.GetString("WorkerInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A worker couldn&apos;t be found matching that Match ID..
        /// </summary>
        internal static string WorkerNotFound {
            get {
                return ResourceManager.GetString("WorkerNotFound", resourceCulture);
            }
        }
    }
}
