//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ss.Internal.Management.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ss.Internal.Management.Server.Resources.Strings.es", typeof(Strings_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modo auto ya está en ejecución. Páralo con &apos;&gt;stop&apos;.
        /// </summary>
        internal static string AutoAlreadyEngaged {
            get {
                return ResourceManager.GetString("AutoAlreadyEngaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modo auto ya estaba parado..
        /// </summary>
        internal static string AutoAlreadyStopped {
            get {
                return ResourceManager.GetString("AutoAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibles: {0}.
        /// </summary>
        internal static string AvailableMaps {
            get {
                return ResourceManager.GetString("AvailableMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volviendo al modo auto. Empezando en breve....
        /// </summary>
        internal static string BackToAuto {
            get {
                return ResourceManager.GetString("BackToAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, {0}, indica en el chat tu BAN (ej.: NM1, HD2).
        /// </summary>
        internal static string BanCall {
            get {
                return ResourceManager.GetString("BanCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo azul ha baneado el {0}..
        /// </summary>
        internal static string BlueBanned {
            get {
                return ResourceManager.GetString("BlueBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo azul ha pickeado el {0}..
        /// </summary>
        internal static string BluePicked {
            get {
                return ResourceManager.GetString("BluePicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo azul ha pedido un timeout. El tiempo será añadido una vez el timer actual se acabe..
        /// </summary>
        internal static string BlueTimeout {
            get {
                return ResourceManager.GetString("BlueTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo azul gana el mapa! ({0} vs. {1}).
        /// </summary>
        internal static string BlueWins {
            get {
                return ResourceManager.GetString("BlueWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando canal y cerrando proceso....
        /// </summary>
        internal static string DeletingChannel {
            get {
                return ResourceManager.GetString("DeletingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activando el modo autoreferee para fase eliminatoria, Lobby {0}.
        /// </summary>
        internal static string EngagingAuto {
            get {
                return ResourceManager.GetString("EngagingAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error durante la ejecución del AutoRef: `{0}`.
        /// </summary>
        internal static string ErrAutoref {
            get {
                return ResourceManager.GetString("ErrAutoref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No se encontró el canal con ID {0}.
        /// </summary>
        internal static string ErrChannelNotFound {
            get {
                return ResourceManager.GetString("ErrChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al iniciar AutoRef: {0}.
        /// </summary>
        internal static string ErrInitAutoref {
            get {
                return ResourceManager.GetString("ErrInitAutoref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Error**: El archivo debe ser `.txt` ó `.csv`.
        /// </summary>
        internal static string ErrorNotCorrectFileExtension {
            get {
                return ResourceManager.GetString("ErrorNotCorrectFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Match `{0}` ya está en curso .
        /// </summary>
        internal static string MatchAlreadyCreated {
            get {
                return ResourceManager.GetString("MatchAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Match `{0}` fue iniciado correctamente en su debido thread..
        /// </summary>
        internal static string MatchCreated {
            get {
                return ResourceManager.GetString("MatchCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partido finalizado. Archivando hilo &lt;#{0}&gt;....
        /// </summary>
        internal static string MatchFinishedGlobal {
            get {
                return ResourceManager.GetString("MatchFinishedGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **El partido ha finalizado.** Este hilo será archivado..
        /// </summary>
        internal static string MatchFinishedThread {
            get {
                return ResourceManager.GetString("MatchFinishedThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando cierre para la match `{0}`....
        /// </summary>
        internal static string MatchFinishingUp {
            get {
                return ResourceManager.GetString("MatchFinishingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La match `{0}` no fue encontrada en la base de datos..
        /// </summary>
        internal static string MatchNotFound {
            get {
                return ResourceManager.GetString("MatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GGWP! {0} gana el partido!.
        /// </summary>
        internal static string MatchWin {
            get {
                return ResourceManager.GetString("MatchWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninguno.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insuficientes argumentos..
        /// </summary>
        internal static string NotEnoughArgs {
            get {
                return ResourceManager.GetString("NotEnoughArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@&amp;{0}&gt;, {1} ha solicitado intervención humana. El modo auto ha sido deshabilitado, para reanudarlo usa !panic_over.
        /// </summary>
        internal static string Panic {
            get {
                return ResourceManager.GetString("Panic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, {0}, indica en el chat tu PICK (ej.: NM1, HD2).
        /// </summary>
        internal static string PickCall {
            get {
                return ResourceManager.GetString("PickCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedades no inicializadas. Rellena first_ban y first_pick.
        /// </summary>
        internal static string PropertiesNotInit {
            get {
                return ResourceManager.GetString("PropertiesNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activando el modo autoreferee para fase clasificatoria, Lobby {0}. Usa &apos;!panic&apos; si necesitas intervención humana y un referee estará contigo a la mayor brevedad posible..
        /// </summary>
        internal static string QualifiersAutoEngage {
            get {
                return ResourceManager.GetString("QualifiersAutoEngage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby de qualifiers terminada. Gracias por jugar!.
        /// </summary>
        internal static string QualifiersOver {
            get {
                return ResourceManager.GetString("QualifiersOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo rojo ha baneado el {0}..
        /// </summary>
        internal static string RedBanned {
            get {
                return ResourceManager.GetString("RedBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo rojo ha pickeado el {0}..
        /// </summary>
        internal static string RedPicked {
            get {
                return ResourceManager.GetString("RedPicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo rojo ha pedido un timeout. El tiempo será añadido una vez el timer actual se acabe.
        /// </summary>
        internal static string RedTimeout {
            get {
                return ResourceManager.GetString("RedTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo rojo gana el mapa! ({0} vs. {1}).
        /// </summary>
        internal static string RedWins {
            get {
                return ResourceManager.GetString("RedWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee {0} añadido/actualizado en la base de datos \n- OsuID: {1}\n- DiscordID: {2}.
        /// </summary>
        internal static string RefAddedToDb {
            get {
                return ResourceManager.GetString("RefAddedToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Referee **{0}** ha sido asignado con éxito a la match `{1}`.
        /// </summary>
        internal static string RefAssignedSuccessfully {
            get {
                return ResourceManager.GetString("RefAssignedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Referee `{0}` no existe en la base de datos. Usa `/linkirc` para añadirle.
        /// </summary>
        internal static string RefDoesntExist {
            get {
                return ResourceManager.GetString("RefDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout pedido por el referee del partido. El tiempo será añadido una vez el timer actual se acabe.
        /// </summary>
        internal static string RefTimeout {
            get {
                return ResourceManager.GetString("RefTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La segunda ronda de bans va a comenzar.
        /// </summary>
        internal static string SecondBanRound {
            get {
                return ResourceManager.GetString("SecondBanRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modo auto está en ejecución, desactívalo para poner mapas de forma manual..
        /// </summary>
        internal static string SetMapFail {
            get {
                return ResourceManager.GetString("SetMapFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asigna un referee a una match concreta..
        /// </summary>
        internal static string SlashCommandAssignRef {
            get {
                return ResourceManager.GetString("SlashCommandAssignRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acaba con el entorno de match activo y archiva en hilo donde ocurrió.
        /// </summary>
        internal static string SlashCommandEndRef {
            get {
                return ResourceManager.GetString("SlashCommandEndRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sube un .csv con la herramienta de LeoFLT para parsearlo y guardar las scores.
        /// </summary>
        internal static string SlashCommandImportScoresPrivate {
            get {
                return ResourceManager.GetString("SlashCommandImportScoresPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configura tus credenciales de IRC para poder crear matches.
        /// </summary>
        internal static string SlashCommandLinkIrc {
            get {
                return ResourceManager.GetString("SlashCommandLinkIrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia una nueva interfaz de match entre discord y Bancho, usando las credenciales de IRC para un Referee..
        /// </summary>
        internal static string SlashCommandStartRef {
            get {
                return ResourceManager.GetString("SlashCommandStartRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parando el modo auto....
        /// </summary>
        internal static string StoppingAuto {
            get {
                return ResourceManager.GetString("StoppingAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first_ban rellenado satisfactoriamente..
        /// </summary>
        internal static string SuccessfulFirstBan {
            get {
                return ResourceManager.GetString("SuccessfulFirstBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first_pick rellenado satisfactoriamente..
        /// </summary>
        internal static string SuccessfulFirstPick {
            get {
                return ResourceManager.GetString("SuccessfulFirstPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout rojo disponible: {0} | Timeout azul disponible: {1}.
        /// </summary>
        internal static string TimeoutAvailable {
            get {
                return ResourceManager.GetString("TimeoutAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empezando timeout, recuerda estar listo/pickear/banear antes de que acabe!.
        /// </summary>
        internal static string TimeoutStart {
            get {
                return ResourceManager.GetString("TimeoutStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal creado para Referee: **{0}**. Iniciando worker....
        /// </summary>
        internal static string WorkerInit {
            get {
                return ResourceManager.GetString("WorkerInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró un worker activo con ese Match ID..
        /// </summary>
        internal static string WorkerNotFound {
            get {
                return ResourceManager.GetString("WorkerNotFound", resourceCulture);
            }
        }
    }
}
